Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: uestc_123YEYE
  Host: 127.0.0.1:3306
  DBName: web_service
  # TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60000000
  WriteTimeout: 60000000